Update to Swift 3 / Xcode 8
mdsol/appconnect-ios pull request #49
Opened 2016-11-08 21:38 UTC by ncarroll-mdsol

This PR updates the app to use Swift 3 / Xcode 8. A few notes:

- Had to add the Keychain access utility to avoid an error when getting the user's password
- Had to add an Info.plist entry to access the photo library
- Updated the IQ keyboard manager to the latest version

We can do a lot more to clean up this app in the future, but this will at least make it compatible.

2016-11-08 22:09 UTC, sroymdsol requested changes

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift.xcodeproj/project.pbxproj
> +							com.apple.Keychain = {
I believe this could be the same red herring as I had to work around in Garuda and NewWalk. It is described here, with a link to the less invasive solution: https://jira.mdsol.com/browse/MCC-245647

This is the commit for how I did it in NewWalk:
https://github.com/mdsol/newwalk/commit/29fa08eb1c38715696351639ea339c9e5b7222e6

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/CaptureImageViewController.swift
> +                OperationQueue.main.addOperation({
Are we able to get rid of the parens enclosing the closure here?

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/CaptureImageViewController.swift
> +                OperationQueue.main.addOperation({
Same thing in many other places in this PR.

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/CreateAccountViewController.swift
> +        let client = clientFactory.client(of: MDClientType.hybrid);
Can the `MDClientType` prefix be omitted here?

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/FieldViewController.swift
>          ][problem]!
Isn't it wasteful to declare a dictionary only to pick a value out of it? Seems like we should make it a variable so it's only created once.

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/FormListViewController.swift
> +        self.dismiss(animated: true, completion: nil)
Nitpick: `completion` defaults to nil so can be omitted.

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/FormListViewController.swift
> +        self.dismiss(animated: true, completion: nil)
Nitpick: Also don't need the `self.` prefix, although it doesn't hurt.

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/ModelController.swift
> +    fileprivate var fields: [MDField] = []
Isn't `private` enough here since the enclosing declaration is the ModelController?

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/ModelController.swift
> +    fileprivate var fields: [MDField] = []
Nitpick: We could do a find and replace of "= []" to just "()".

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/MultiPageFormViewController.swift
> +    fileprivate var form : MDForm!
Nitpick: This file uses spaces before the `:`, which is a bit odd. I only use it in dictionary declarations.

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/MultiPageFormViewController.swift
> +        if stepSequencer.state == MDStepSequencerState.reviewing {
Nitpick: I think the `MDStepSequencerState.` prefix is not needed here?

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/OnePageFormViewController.swift
> +            switch (field as AnyObject).fieldOID {
This compiles? I thought since the type is cast to AnyObject, that `.fieldOID` wouldn't be recognized…

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/OnePageFormViewController.swift
> +        sequencer?.start()
Would it be worth unwrapping or guarding the `sequencer` constant so we don't have to jump through hoops in the rest of this method?

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/PasswordViewController.swift
> +        confirmPasswordsMatching.isHidden =  true
Nitpick: Space trouble.

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/SecurityQuestionViewController.swift
> +        cell.textLabel?.lineBreakMode = NSLineBreakMode.byWordWrapping
Nitpick: Not sure `NSLineBreakMode.` prefix is needed here?

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/UIViewController+Extensions.swift
> +        return (UIApplication.shared.delegate as! AppDelegate).UIDatastore!
Just an observation: It's funny that for UIApplication, `shared` is a property but for NSApplication it's a `shared()` method.

2016-11-08 22:09 UTC, sroymdsol commented on AppConnectSwift/UIViewController+Extensions.swift
> +        alert.addAction(UIAlertAction(title: "OK", style: UIAlertActionStyle.default) { alert in completion?() })
Nitpick: Would be nice to expand this closure into a separate line. Always nice to setting breakpoints and understanding what's going on.

2016-11-08 22:09 UTC, sroymdsol commented on Podfile
> +pod 'IQKeyboardManagerSwift'
Enforcing the version is always a good idea. We can be loose and just say 4.0 if we're not picky.

2016-11-08 22:44 UTC, ncarroll-mdsol commented on AppConnectSwift/ModelController.swift
> +    fileprivate var fields: [MDField] = []
Sure - the auto-conversion chose fileprivate so I went with it. Updated! I don't think that find/replace will work, since you also have to replace the `:` with `=`

2016-11-08 22:46 UTC, ncarroll-mdsol commented on AppConnectSwift/OnePageFormViewController.swift
> +            switch (field as AnyObject).fieldOID {
Yeah, that is strange... also done by the autoconversion. Will fix!

2016-11-08 22:48 UTC, ncarroll-mdsol commented on AppConnectSwift/OnePageFormViewController.swift
> +        sequencer?.start()
Absolutely - this is one of those instances where I think we need to add some annotations in the library so that the init doesn't return an optional. I'd like to keep these as-is until that fix is made, though.

2016-11-08 22:51 UTC, ncarroll-mdsol commented on Podfile
> +pod 'IQKeyboardManagerSwift'
Sure - I figured the version is enforced in the .lock, and we update this project frequently enough that it'd be fine if a `pod update` grabbed the latest. But, also no harm in being a bit more explicit.

2016-11-08 22:59 UTC, ncarroll-mdsol commented on AppConnectSwift.xcodeproj/project.pbxproj
> +							com.apple.Keychain = {
Ah, good call - fixed!

2016-11-09 13:36 UTC, sroymdsol commented on AppConnectSwift/OnePageFormViewController.swift
> +        sequencer?.start()
Makes sense.

2016-11-09 13:52 UTC, sroymdsol commented
With the entitlements workaround added, the keychain sharing capability can be turned back off.

I'm also pretty sure the entitlements workaround is only needed for the Debug configuration.

2016-11-09 15:25 UTC, ncarroll-mdsol commented
Is there any downside to having it for the non-debug configuration? The keychain sharing should be off - it was removed from the entitlements file.

2016-11-09 15:30 UTC, sroymdsol commented
I'm not sure if there are downsides to having it for the release configuration. Since it's a workaround, I made the smallest possible change when I applied it to other projects, just to be safe.

Regarding the capability, it still appears turned on in the project under Targets > AppConnectSwift > Capabilities > Keychain Sharing.

2016-11-09 15:41 UTC, ncarroll-mdsol commented
Ah, you're right - fixed! Also moved the option to just the debug entitlements.

2016-11-09 15:43 UTC, sroymdsol approved these changes

2016-11-09 18:08 UTC, kbohlmann-mdsol commented
🎊

2016-11-09 18:08 UTC, merged