update readme for security question change
mdsol/appconnect-ios pull request #61
Opened 2018-06-19 17:10 UTC by agodel

This updates the readme to reflect the newest babbage and api version where deprecated questions cannot be used to enroll subjects.  Necessary for the release of babbage since this is referenced in official documentation.

@ChazzMaTazz

2018-06-19 17:12 UTC, ChazzMaTazz commented
@agodel Will this also include any updates to the sample app or is that a separate PR?

2018-06-19 17:20 UTC, agodel commented
@ChazzMaTazz this is the sample app, but the code has already been updated

2018-06-20 14:09 UTC, ncarroll-mdsol requested changes

2018-06-20 14:09 UTC, ncarroll-mdsol commented on README.md
> +var validQuestions = [[String: AnyHashable]]()
Can this be `String : String`?

2018-06-20 14:09 UTC, ncarroll-mdsol commented on README.md
> +        let questions = response?["security_questions"] as? [[String: AnyHashable]] else {
Similarly can this be `String: String`?

2018-06-20 14:09 UTC, ncarroll-mdsol commented on README.md
> +        for (question) in questions {
Are the parens necessary?

2018-06-20 14:09 UTC, ncarroll-mdsol commented on README.md
> +// JSON returned is structured
Minor nitpick: would be more readable if this were a full sentence "The returned JSON is structured:`

2018-06-20 14:09 UTC, agodel commented on README.md
> +var validQuestions = [[String: AnyHashable]]()
no there is a bool and an int

2018-06-20 14:12 UTC, ncarroll-mdsol commented on README.md
> +var validQuestions = [[String: AnyHashable]]()
Ooh, right.

2018-06-20 14:12 UTC, ncarroll-mdsol approved these changes

2018-06-20 14:12 UTC, merged